fidesmo/fdsm

- src/main/java/com/fidesmo/fdsm/FidesmoCard.java
- src/main/java/com/fidesmo/fdsm/ServiceDeliverySession.java
Mifare services can only be delivered to devices having a Mifare emulation. The Fidesmo platform checks it by reading the device's capabilities before attempting to deliver the service.
This PR reads the Mifare Type tag (0x42) and sends it to the server in the delivery request, within the `capabilities` structure.
> Read and transmit MifareType capability

- src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- src/main/java/com/fidesmo/fdsm/Main.java
- src/main/java/com/fidesmo/fdsm/ServiceDeliverySession.java
No fdsm will exit either 0 or 1 depending on successful or failing service run.
--run was added to command line interface, but ignored by internal logic. That is also fixed now.
> Fix --run detection and signal service status as process exit code

- src/main/java/com/fidesmo/fdsm/Main.java
--reader is tailored for command line usage (which is usually lower case) but the input was not forced to be lower case. So a proper reader name copy-pasted would not match. That is now fixed
> bug: compare lower case reader name with lower case input argument

- src/main/java/com/fidesmo/fdsm/FidesmoCard.java
Without it SECID chips honour the request and send no FCI in response to SELECT commands
> Fix #20: correctly set Le for SELECT commands when listing apps

- pom.xml
- src/main/java/com/fidesmo/fdsm/AuthenticatedFidesmoApiClient.java
- src/main/java/com/fidesmo/fdsm/CommandLineFormHandler.java
- src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- src/main/java/com/fidesmo/fdsm/FidesmoCard.java
- src/main/java/com/fidesmo/fdsm/FormHandler.java
- src/main/java/com/fidesmo/fdsm/Main.java
- src/main/java/com/fidesmo/fdsm/ServiceDeliverySession.java
- Make use of CallbackHandlers and Logger from ServiceDeliverySession
- Allow to specify the output stream where FidesmoApiClient trace is written to
- Introduce timeouts and retries to service delivery (default is 10 minutes)
- Make FormHandler also implement CallbackHandler
- Introduce a special --qa argument and ability to fake a Fidesmo card
> Preparations for next version

- src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- src/main/java/com/fidesmo/fdsm/ServiceDeliverySession.java
When doing a delivery it is advised to provide CIN of the card to service, that allows to properly compute price for specific card and allow redelivery in FDSM if it's free.
> adds support of paid services redelivery

- src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
In case the service provider is slow sec-server can return `204` status for some commands, which requires retry from the client. Limited to a sane number of retries and timeout.
> slow providers support added

- src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- src/main/java/com/fidesmo/fdsm/ServiceDeliverySession.java
The only endpoint where `204` status implies retry is the service fetch, but there are other endpoints where `204` status means simply no data. 
So this PR changes API client so:
* FidesmoAPI returns `null` on 204 status. We should consider using `Optional` instead, but for now that breaks API too much. Anyway it's better than retrying and failing with parsing exception.
* Retry logic moved to exact place where it's necessary – delivery request.
> Fixed API retry logic

- library/pom.xml
- library/src/main/java/com/fidesmo/fdsm/AuthenticatedFidesmoApiClient.java
- library/src/main/java/com/fidesmo/fdsm/ClientAuthentication.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoCard.java
- library/src/main/java/com/fidesmo/fdsm/UserCancelledException.java
- library/src/main/java/com/fidesmo/fdsm/WsClient.java
- tool/src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- tool/src/main/java/com/fidesmo/fdsm/Main.java
Fidesmo API now supports Web Sockets for certain operations (at the moment only APDU exchange). This PR adds support of running web socket operations using the same `run` command. 
Also as Fidesmo API now supports generic credentials and not only `appId/appKey` for authentication, it is proposed to add a new option `auth` (with `$FDSM_AUTH` env variable) and use it everywhere.
So the complete example of WS execution:
```
fdsm --trace-apdu --verbose --auth test:test --run ws://url
```
> Web socket support

- library/src/main/java/com/fidesmo/fdsm/AuthenticatedFidesmoApiClient.java
- library/src/main/java/com/fidesmo/fdsm/ClientAuthentication.java
- library/src/main/java/com/fidesmo/fdsm/FDSMException.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoCard.java
- library/src/main/java/com/fidesmo/fdsm/NotSupportedException.java
- library/src/main/java/com/fidesmo/fdsm/RecipeGenerator.java
- library/src/main/java/com/fidesmo/fdsm/ServiceDeliverySession.java
- library/src/main/java/com/fidesmo/fdsm/WsClient.java
- library/src/test/java/com/fidesmo/fdsm/FidesmoCardTest.java
- library/src/test/java/com/fidesmo/fdsm/TestChannel.java
- tool/src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- tool/src/main/java/com/fidesmo/fdsm/Main.java
This makes the separation between Fidesmo metadata and transport mechanisms more clear, whereas existing layout a bit more messy. Removes the need for --fake.
Includes some style changes (Optional in arguments)
> Make FidesmoCard a purely metadata class

- library/src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoCard.java
- tool/src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- tool/src/main/java/com/fidesmo/fdsm/Main.java
* Adds support for new authentication method for upload, install, uninstall, store data etc. functions by introducing new parameter `app-id`.
Adds changes proposed by @ckahlo to make client compatible with Java 8.
> Token authentication support for upload

- library/src/main/java/com/fidesmo/fdsm/AuthenticatedFidesmoApiClient.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- tool/src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- tool/src/main/java/com/fidesmo/fdsm/Main.java
* Migrated to new CAP management endpoints that requires appId explicitly
* Removed `/v2/` prefix as now both versions are compatible, so prefix is not necessary.
> Using updated CAP management URLs

- tool/src/main/java/com/fidesmo/fdsm/Main.java
OS version field is an optional field so we need to expect that it might be absent. Also moved to a new `osTypeVersionName` field name.
> Fixed OS type version parsing

- library/src/main/java/com/fidesmo/fdsm/DeliveryUrl.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoCard.java
- library/src/main/java/com/fidesmo/fdsm/ServiceDeliverySession.java
- library/src/test/java/com/fidesmo/fdsm/DeliveryUrlTest.java
- library/src/test/java/com/fidesmo/fdsm/FidesmoCardTest.java
- tool/src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- tool/src/main/java/com/fidesmo/fdsm/Main.java
Adds ability to automatically batch devices post issuence.
How it works? 
* `FidesmoCard` now have online and offline device identification options, where online version tries to identify device by the CPLC data on the server as the last resort
* Implicit batching for operations that require a Fidesmo device, like installation, store-data etc
* On device info command we only print instructions of how to do batching manually without performing any changes
Other related changes:
* As `batchId` in the `FidesmoCard` can be obtained from the server it moved to integer, breaking change, but AFAIK it's only used internally and was always converted to int every time, so better to have it correct as soon as possible.
* Added a batched flag to the `FidesmoCard`.
* Added a `DeliveryUrl` parser, as …
> Devices batching support added

- library/src/main/java/com/fidesmo/fdsm/FidesmoApiClient.java
- library/src/main/java/com/fidesmo/fdsm/FidesmoCard.java
- library/src/test/java/com/fidesmo/fdsm/FidesmoCardTest.java
- tool/src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- tool/src/main/java/com/fidesmo/fdsm/Main.java
The UID is required for checking to which concrete UID-range belongs some batch that will be assigned to the device
> Added UID for identifying unbatched device

- library/src/main/java/com/fidesmo/fdsm/ClientAuthentication.java
If a password contains the character ":" right now we return an exception, according to [the Basic Auth Scheme](https://datatracker.ietf.org/doc/html/rfc7617) it should be allowed in password and not in username. Since we receive the auth string as a whole we have no way of knowing if many colons are intended or not.
We can simply assume the string is valid and limit the split to 1 parition ([.split() command](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#split(java.lang.String,int)) limit parameter refers to the max number of resulting elements).
> Limit to 1 regex application while checking basic auth.

- tool/pom.xml
This PR attempts to fix launch4j configuration, as starting from launch4j 3.50 JRE path [is required](https://launch4j.sourceforge.net/docs.html#Configuration_file). The 3.50 version [was published](https://mvnrepository.com/artifact/net.sf.launch4j/launch4j) after the last successfull release and even though we haven't updated the launch4j version ourselves, it seems the plugin takes the latest one automatically. 
Locally the change works, so hope GH Action will like it as well.
> Fixes launch4j publishing on release

- tool/pom.xml
As corrected by @martinpaljak this setting is a runtime path on the client side, not the one used during build. So setting it to defaults that older version of the launch4j was providing.
> Fijex JRE runtime path

- tool/src/main/java/com/fidesmo/fdsm/CommandLineInterface.java
- tool/src/main/java/com/fidesmo/fdsm/Main.java
This makes working interactively from CLI more pleasant. Both appID and authentication can be set in the environment (direnv, ondir etc)
> Do not require --app-id and support getting it from environment

- library/src/main/java/com/fidesmo/fdsm/FidesmoCard.java
- library/src/main/java/com/fidesmo/fdsm/ServiceDeliverySession.java
- tool/src/main/java/com/fidesmo/fdsm/Main.java
Add empty select after checking card info.
Checking card info perform some selects that may leave the FPA selected, this prevents some services to be run.
> Add empty select after checking card info

- tool/src/main/java/com/fidesmo/fdsm/Main.java
Fields parser was breaking when specifying complex fields like `field=http://site.com?query=test` because it has two `=` signs in it. This PR fixes that problem
> Slightly improved CLI fields parser

- library/src/main/java/com/fidesmo/fdsm/FidesmoCard.java
Empty select had invalid P1 parameter, it should be 04 `Select by name`. It was actually being processed by Platform Applet or Storage Applet, selected in the pre-delivery information fetching.
The proper command was actually already present under the name `selectISD` since an empty select is used to select the ISD.
Removed buggy method and updated name for ISD select to specify it's an empty select.
> Fix empty select APDU
